config/routes.rb
Rails.application.routes.draw do



   devise_for :admins, controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
    registrations: 'admin/registrations'
  }
  root to: 'homes#top'
  
  get  "about"  => "homes#about"

  scope module: :public do

    get 'customers/my_page' => 'customers#show'
    get 'customers/edit' => 'customers#edit'
    patch 'customers' => 'customers#update'
    get 'customers/unsubscribes' => 'customers#unsubscribes'
    patch '/customers/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    resources :addresses, only: [:index, :edit, :update, :destroy, :create]
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    post 'orders/comfirm' => 'orders#comfirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders

  end

   devise_for :customers, controllers: {
    sessions:      'public/sessions',
    passwords:     'public/passwords',
    registrations: 'public/registrations'
  }

  namespace :admin do

    resources :items
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]
    root to: 'homes#top'

  end
 end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  validates :address, presence: true
  validates :postal_code, presence: true
  validates :name, presence: true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
   belongs_to :item
   belongs_to :customer
   
      def subtotal
         item.with_tax_price * amount
      end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def active_for_authentication?
    super && (is_deleted == false)
  end

    has_many :cart_items, dependent: :destroy
    has_many :orders, dependent: :destroy
    has_many :addresses, dependent: :destroy

  def full_name
    self.last_name.to_s + " " + self.first_name.to_s
  end


end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
      attachment :image
      has_many :cart_items, dependent: :destroy
      has_many :order_details, dependent: :destroy


      def with_tax_price
          (price * 1.1).floor
      end



end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  belongs_to :customer
  has_many :order_details

      def with_tax_price
          (price * 1.1).floor
      end
      def subtotal
         item.with_tax_price * amount
      end    
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
   belongs_to :item
   belongs_to :order
      def with_tax_price
          (price * 1.1).floor
      end
      def subtotal
         item.with_tax_price * amount
      end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
   @orders = Order.all

  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
  @item = Item.new
  end

def create
   @item = Item.new(item_params)
  if @item.save
    redirect_to request.referer
  else
    render :new
  end
end

  def index
   @items = Item.all

  end

  def show
   @item = Item.find(params[:id])

  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_items_path(item)
  end

  def edit
   @item = Item.find(params[:id])

  end




  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre, :price)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

def show
 @order =  Order.find(params[:id])
end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
        admin_root_path
    else
        root_path
    end
end

def
after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
end






  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  @items = Item.limit(4).order(created_at: :desc)

  end
  def about
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/items/edit.html.erb
<!DOCTYPE html>
<div class="col-md-8 offset-md-1">

<h2>商品編集</h2>
<%= form_with model:@item,url: admin_item_path(@item), local:true do |f| %>

  <h4>商品画像</h4>
  <%= f.attachment_field :image %>
  <h4>商品名</h4>
  <%= f.text_field :name %>
  <h4>商品説明</h4>
  <%= f.text_area :introduction %>
  <h4>税抜価格</h4>
  <%= f.number_field :price %>
  <%= f.submit '変更を保存' ,class: 'btn btn-success'  %>
<% end %>
</div>

app/views/admin/items/index.html.erb
<!DOCTYPE html>
<div class="col-md-8 offset-md-1">
 <h2>商品一覧</h2>
<div class = "new">
  <%= link_to '＋', new_admin_item_path %>
</div>

  <table class="table table-hover table-inverse">
   <thead>
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<tbody>
<% @items.each do |item| %>
<tr>
  <td>
   <%= item.id %>
  </td>
  <td>
   <%= link_to item.name, "/admin/items/#{item.id}" %>
  </td>
  <td>
   <%= item.price. to_s(:delimited)%>
  </td>
 </div>
 <% end %>

</tbody>

 </table>
</div>
</main>

app/views/admin/items/new.html.erb
<!DOCTYPE html>
<div class="col-md-8 offset-md-1">
<h3>商品新規登録</h3>
<%= form_with model:@item,url: admin_items_path, local:true do |f| %>


<div class="row">
 <table class="table table-hover table-borderless">
　<tr>
   <td>商品画像</td>
   <td>
    <%= f.attachment_field :image %>
   </td>
 </tr>
  <tr>
   <td>商品名</td>
   <td>
    <%= f.text_field :name %>
   </td>
  </tr>
  <tr>
   <td>商品説明</td>
   <td>
    <%= f.text_area :introduction %>
   </td>
 </tr>
 <tr>
   <td>税抜価格</td>
   <td>
    <%= f.number_field :price %>円
   </td>
 </tr>
 <tr>
   <td>
  <%= f.submit '新規登録', class: 'btn btn-success' %>
   </td>
 </tr>
 <% end %>

  </table>
</div>

app/views/admin/items/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 <body>
<div class = "container">
 <h2>商品詳細</h2>
</div>
<div class="row">
　<div class ="col-1">
  </div>
 <div class ="col-3">
  <%= attachment_image_tag @item, :image, :fill, 300, 300 %>
  </div>
  <div class ="col-7">

  <table class="table table-hover table-inverse">

    <tbody>

     <tr>
      <td>商品名：</td><td> <%= @item.name %></td>
     </tr>

     <tr>
      <td>商品説明：</td><td> <%= @item.introduction %></td>
     </tr>

     <tr>
      <td>税抜価格：</td><td> <%= @item.price. to_s(:delimited) %> 円</td>
     </tr>

 </table>

 </div>

</div>
<div class = "edit">
 <%= link_to "編集する", edit_admin_item_path(@item) ,class: 'btn btn-success'%>
</div>

app/views/admin/orders/show.html.erb
   <% @totle =0 %>
   <% @order.order_details.each do |order_detail| %>
   <% order_detail.subtotal %> <% @totle += order_detail.subtotal %>
   <% end %>
   <% @totle .to_s(:delimited)%>
<div class = "container">
 <h5>注文履歴詳細</h5>
  <div class="row">
   <table class="table table-hover table-inverse">
   <thead>
   </thead>
     <tbody>
        <tr>
          <td>購入者</td><td><%= link_to @order.customer.full_name , "admin_customers_path(customer.id)" %></td>
        </tr>
        <tr>
          <td>注文日</td><td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <td>配送先</td><td>〒<%= @order.postal_code.to_s.insert(3, "-") %>  <%= @order.address %><br><%= @order.name %></td>
        </tr>
        <tr>
          <td>支払方法</td><td><%= @order.payment_method_i18n %></td>
        </tr>
     </tbody>
    </table>
   <table class="table table-hover table-inverse">
     <thead>
        <tr>
          <th>商品名</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
          <th colspan="3"></th>
        </tr>
     </thead>
     <tbody>
        <% @order.order_details.each do |order_detail| %>
         <tr>
             <td> <%= order_detail.item.name %> </td>
             <td><%= order_detail.item.with_tax_price.to_s(:delimited)%> </td>
             <td><%= order_detail.amount %></td>
             <td><%= order_detail.subtotal %>  </td>
             <% end %>
         <tr>
     </tbody>
   </table>
    <table class="table table-hover table-inverse">
     <thead>
     </thead>
       <tbody>
            <tr>
              <td>
                <td>商品合計</td><td><%= @totle .to_s(:delimited)%>円</td>
              </td>
            </tr>

            <tr>
              <td>
                <td>送料</td><td><%= @order.shipping_cost %>円</td>
              </td>
            </tr>

            <tr>
             <td>
                 <td>請求金額合計</td><td><%= @order.total_payment.to_s(:delimited) %>円</td>
             </td>
            </tr>
      </tbody>
    </table>
 </div>
</div>