config/routes.rb
Rails.application.routes.draw do



   devise_for :admins, controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
    registrations: 'admin/registrations'
  }
  root to: 'homes#top'
  
  get  "about"  => "homes#about"

  scope module: :public do

    get 'customers/my_page' => 'customers#show'
    get 'customers/edit' => 'customers#edit'
    patch 'customers' => 'customers#update'
    get 'customers/unsubscribes' => 'customers#unsubscribes'
    patch '/customers/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    resources :addresses, only: [:index, :edit, :update, :destroy, :create]
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    post 'orders/comfirm' => 'orders#comfirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders

  end

   devise_for :customers, controllers: {
    sessions:      'public/sessions',
    passwords:     'public/passwords',
    registrations: 'public/registrations'
  }

  namespace :admin do

    resources :items
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]
    root to: 'homes#top'

  end
 end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  validates :address, presence: true
  validates :postal_code, presence: true
  validates :name, presence: true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
   belongs_to :item
   belongs_to :customer
   
      def subtotal
         item.with_tax_price * amount
      end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def active_for_authentication?
    super && (is_deleted == false)
  end

    has_many :cart_items, dependent: :destroy
    has_many :orders, dependent: :destroy
    has_many :addresses, dependent: :destroy

  def full_name
    self.last_name.to_s + " " + self.first_name.to_s
  end


end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
      attachment :image
      has_many :cart_items, dependent: :destroy
      has_many :order_details, dependent: :destroy


      def with_tax_price
          (price * 1.1).floor
      end



end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  belongs_to :customer
  has_many :order_details

      def with_tax_price
          (price * 1.1).floor
      end
      def subtotal
         item.with_tax_price * amount
      end    
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
   belongs_to :item
   belongs_to :order
      def with_tax_price
          (price * 1.1).floor
      end
      def subtotal
         item.with_tax_price * amount
      end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
   @customers = Customer.all
  end

  def show
   @customer = Customer.find(params[:id])
   @address = Address.find(params[:id])
  end

  def edit
   @customer = Customer.find(params[:id])
  end

  def update
   customer = Customer.find(params[:id])
   customer.update(customer_params)
   redirect_to admin_customer_path(customer)
  end

  private
  def customer_params
   params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
   @orders = Order.all

  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
  @item = Item.new
  end

def create
   @item = Item.new(item_params)
  if @item.save
    redirect_to request.referer
  else
    render :new
  end
end

  def index
   @items = Item.all

  end

  def show
   @item = Item.find(params[:id])

  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_items_path(item)
  end

  def edit
   @item = Item.find(params[:id])

  end




  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre, :price)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

def show
 @order =  Order.find(params[:id])
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
        admin_root_path
    else
        root_path
    end
end

def
after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
end






  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  @items = Item.limit(4).order(created_at: :desc)

  end
  def about
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/customers/edit.html.erb
<div class = "container">
<%= form_with model:@customer,url: admin_customer_path(@customer), local:true do |f| %>

<h3><%= @customer.last_name %> <%= @customer.first_name %>さんの会員情報編集</h3>

<div class="row">
  <table class="table table-hover table-borderless">

  <tr>
    <td>会員ID</td>
    <td>
       <%= @customer.id %>
    </td>
  </tr>

  <tr>
    <td>氏名</td>
    <td> <%= f.text_field :last_name %>  <%= f.text_field :first_name %></td>
  </tr>

   <tr>
    <td>フリガナ</td>
    <td><%= f.text_field :last_name_kana %>  <%= f.text_field :first_name_kana %></td>
   </tr>

   <tr>
    <td>郵便番号</td>
    <td><%= f.text_field :postal_code %></td>
   </tr>

  <tr>
    <td>住所</td>
    <td><%= f.text_field :address %></td>
  </tr>

  <tr>
    <td>電話番ナ</td>
    <td><%= f.text_field :telephone_number %></td>
  </tr>

  <tr>
    <td>メールアドレス</td>
    <td> <%= f.text_field :email %></td>
  </tr>

  <tr>
    <td>会員ステータス</td>
    <td><%= f.radio_button :is_deleted, :false %>有効　<%= f.radio_button :is_deleted, :true %>退会</td>
</table>
  <%= f.submit '変更を保存' ,class: 'btn btn-success'  %>
<% end %>


</div>

app/views/admin/customers/index.html.erb
<!DOCTYPE html>
<div class="col-md-8 offset-md-1">
 <h2>会員一覧</h2>
  <table class="table table-hover table-inverse">
   <thead>
    <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<tbody>



<% @customers.each do |customer| %>
<tr>
  <td>
   <%= customer.id %>
  </td>
  <td>
   <%= link_to customer.full_name  , "/admin/customers/#{customer.id}" %>
  </td>
  <td>
   <%= customer.email  %>
  </td>
  <td>
   <% if customer.is_deleted == false %>
    <%= customer.is_deleted = "有効" =%>
   <% else %>
    <%= customer.is_deleted = "無効" =%>
   <% end %>

  </td>
</tr>
 </div>
 <% end %>

</tbody>

 </table>
</div>
</main>

app/views/admin/customers/show.html.erb
<!DOCTYPE html>
<div class="col-md-8 offset-md-1">
<div class = "container">

<h3>会員詳細</h3>

<div class="row">
  <table class="table table-hover table-borderless">
 <tr>
    <td>会員ID</td>
    <td>
     <%= @customer.id %>
    </td>
  </tr>
  <tr>
    <td>氏名</td>
    <td>
     <%= @customer.last_name %> <%= @customer.first_name %>
    </td>
  </tr>
 <tr>
    <td>フリガナ</td>
    <td>
     <%= @customer.last_name_kana %> <%= @customer.first_name_kana %>
    </td>
  </tr>
 <tr>
    <td>郵便番号</td>
    <td>
     <%= @customer.postal_code %>
    </td>
  </tr>
 <tr>
    <td>住所</td>
    <td>
     <%= @customer.address %>
    </td>
  </tr>
 <tr>
    <td>電話番号</td>
    <td>
     <%= @customer.telephone_number %>
    </td>
  </tr>
 <tr>
    <td>メールアドレス</td>
    <td>
     <%= @customer.email %>
    </td>
  </tr>
 <tr>
    <td>会員ステータス</td>
    <td>
     <% if @customer.is_deleted == false %>有効
     <% else %>無効
     <% end %>
    </td>
  </tr>
  </table>
</div>


  <%= link_to "編集する", edit_admin_customer_path(@customer) ,class: 'btn btn-success'%>
  <%= link_to "注文履歴一覧を見る", edit_admin_customer_path(@customer) ,class: 'btn btn-primary'%>


</div>
</div>