config/routes.rb
Rails.application.routes.draw do



   devise_for :admins, controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
    registrations: 'admin/registrations'
  }
  root to: 'homes#top'
  
  get  "about"  => "homes#about"

  scope module: :public do

    get 'customers/my_page' => 'customers#show'
    get 'customers/edit' => 'customers#edit'
    patch 'customers' => 'customers#update'
    get 'customers/unsubscribes' => 'customers#unsubscribes'
    patch '/customers/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    resources :addresses, only: [:index, :edit, :update, :destroy, :create]
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    post 'orders/comfirm' => 'orders#comfirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders

  end

   devise_for :customers, controllers: {
    sessions:      'public/sessions',
    passwords:     'public/passwords',
    registrations: 'public/registrations'
  }

  namespace :admin do

    resources :items
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]
    root to: 'homes#top'

  end
 end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  validates :address, presence: true
  validates :postal_code, presence: true
  validates :name, presence: true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
   belongs_to :item
   belongs_to :customer
   
      def subtotal
         item.with_tax_price * amount
      end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def active_for_authentication?
    super && (is_deleted == false)
  end

    has_many :cart_items, dependent: :destroy
    has_many :orders, dependent: :destroy
    has_many :addresses, dependent: :destroy

  def full_name
    self.last_name.to_s + " " + self.first_name.to_s
  end


end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
      attachment :image
      has_many :cart_items, dependent: :destroy
      has_many :order_details, dependent: :destroy


      def with_tax_price
          (price * 1.1).floor
      end



end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  belongs_to :customer
  has_many :order_details

      def with_tax_price
          (price * 1.1).floor
      end
      def subtotal
         item.with_tax_price * amount
      end    
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
   belongs_to :item
   belongs_to :order
      def with_tax_price
          (price * 1.1).floor
      end
      def subtotal
         item.with_tax_price * amount
      end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
   @orders = Order.all

  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
  @item = Item.new
  end

def create
   @item = Item.new(item_params)
  if @item.save
    redirect_to request.referer
  else
    render :new
  end
end

  def index
   @items = Item.all

  end

  def show
   @item = Item.find(params[:id])

  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_items_path(item)
  end

  def edit
   @item = Item.find(params[:id])

  end




  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre, :price)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

def show
 @order =  Order.find(params[:id])
end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
        admin_root_path
    else
        root_path
    end
end

def
after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
end






  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  @items = Item.limit(4).order(created_at: :desc)

  end
  def about
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/homes/top.html.erb
<!DOCTYPE html>
<div class="col-md-8 offset-md-1">
 <h2>注文履歴一覧</h2>
  <table class="table table-hover table-inverse">
   <thead>
    <tr>
      <th>購入日時</th>
      <th>購入者</th>
      <th>注文個数</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<tbody>
<% @orders.each do |order| %>
<tr>
  <td>
   <%= link_to order.created_at.strftime('%Y/%m/%d %H:%M:%S')  , admin_order_path(order.id)  %>

  </td>
  <td>

 　<%= order.customer.full_name %>


  </td>
  <td>
   <% @totle_amount =0 %>
   <% order.order_details.each do |order_detail| %>
   <% order_detail.amount %> <% @totle_amount += order_detail.amount %>
   <% end %>

 　 <%= @totle_amount %>

  </td>
 </div>
 <% end %>

</tbody>

 </table>
</div>
</main>

app/views/homes/about.html.erb
<div class="mx-auto" style="width: auto;">


  <h1>About</h1>
  <h2>ながのCAKEは全国発送可能なケーキ屋さんです。<br>
  お子様からお年寄りの方までお召し上がりいただけるよう、<br>
  様々なバリエーションを用意しております。<br>
  また、全国へ発送可能ですので「いつ」でも「どこ」でもご注文いただけます。<br>
  ぜひご注文ください。
  </h2>
  <%= image_tag "https://via.placeholder.com/200?text=image", :size =>'700x300' %>
</div>

app/views/homes/top.html.erb
<div class="container-xl">

<div class="card bg-dark text-white">
  <div class="image_tag">
   <%= image_tag "https://via.placeholder.com/200?text=image", :size =>'1068x300' %>
  </div>
  <div class="card-img-overlay">
    <h5 class="card-title">ようこそ、ながのCAKEへ！</h5>
    <p class="card-text">このサイトは、ケーキ販売のE Cサイトになります</p>
    <p class="card-text">会員でない方も商品の閲覧はできますが、</p>
    <p class="card-text">購入には会員登録が必要になります。</p>
  </div>
</div>

 <div class="title">
  <h2>新着商品</h2>
 </div>

  <div class="card-group">
  <% @items.each do |item| %>

  <div class="card">
   <il>
  <%= link_to "/items/#{item.id}" do %>
    <%= attachment_image_tag item, :image, :fill, 250, 250 %>
    <% end %>
   </il>
   <div class="card-body">
     <h5 class="card-title"><%= item.name %></h5>
   <p class="card-text">
   ¥<%= item.price. to_s(:delimited) %>
   </p>
    </div>
     </div>
  <% end %>

  </div>
  <div class = "items">
  <%= link_to '全ての商品を見る', items_path %>
　</div>
</div>