config/routes.rb
Rails.application.routes.draw do



   devise_for :admins, controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
    registrations: 'admin/registrations'
  }
  root to: 'homes#top'
  
  get  "about"  => "homes#about"

  scope module: :public do

    get 'customers/my_page' => 'customers#show'
    get 'customers/edit' => 'customers#edit'
    patch 'customers' => 'customers#update'
    get 'customers/unsubscribes' => 'customers#unsubscribes'
    patch '/customers/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    resources :addresses, only: [:index, :edit, :update, :destroy, :create]
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    post 'orders/comfirm' => 'orders#comfirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders

  end

   devise_for :customers, controllers: {
    sessions:      'public/sessions',
    passwords:     'public/passwords',
    registrations: 'public/registrations'
  }

  namespace :admin do

    resources :items
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]
    root to: 'homes#top'

  end
 end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  validates :address, presence: true
  validates :postal_code, presence: true
  validates :name, presence: true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
   belongs_to :item
   belongs_to :customer
   
      def subtotal
         item.with_tax_price * amount
      end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def active_for_authentication?
    super && (is_deleted == false)
  end

    has_many :cart_items, dependent: :destroy
    has_many :orders, dependent: :destroy
    has_many :addresses, dependent: :destroy

  def full_name
    self.last_name.to_s + " " + self.first_name.to_s
  end


end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
      attachment :image
      has_many :cart_items, dependent: :destroy
      has_many :order_details, dependent: :destroy


      def with_tax_price
          (price * 1.1).floor
      end



end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  belongs_to :customer
  has_many :order_details

      def with_tax_price
          (price * 1.1).floor
      end
      def subtotal
         item.with_tax_price * amount
      end    
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
   belongs_to :item
   belongs_to :order
      def with_tax_price
          (price * 1.1).floor
      end
      def subtotal
         item.with_tax_price * amount
      end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
   @orders = Order.all

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
        admin_root_path
    else
        root_path
    end
end

def
after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
end






  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  @items = Item.limit(4).order(created_at: :desc)

  end
  def about
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<% if admin_signed_in? %>
  <body>
   <body class="d-flex flex-column vh-100">
    <header class="bg-dark text-white">
      <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
          <a class="navbar-brand p-1" href="/admin" >LOGO</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

     <li class="nav-item">
        <%= link_to "商品一覧", admin_items_path ,class: 'nav-link text-white'%>
      </li>
      <li class="nav-item">
        <%= link_to "会員一覧", admin_customers_path ,class: 'nav-link text-white'%>
      </li>
      <li class="nav-item">
        <%= link_to "注文履歴一覧", admin_root_path ,class: 'nav-link text-white'%>
      </li>
      <li class="nav-item">
        <%= link_to "ログアウト", destroy_admin_session_path, method: :delete ,class: 'nav-link text-white'%>
      </li>
<% elsif customer_signed_in? %>
  <body>
   <body class="d-flex flex-column vh-100">
    <header class="bg-dark text-white">
      <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
          <a class="navbar-brand p-1" href="/" >LOGO</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
          <div class="customer_name">
              ようこそ、<%= current_customer.last_name %>さん！
          </div>
      <li class="nav-item">
        <%= link_to "マイページ", customers_my_page_path ,class: 'nav-link text-white'%>
      </li>

     <li class="nav-item">
        <%= link_to "商品一覧", items_path ,class: 'nav-link text-white'%>
      </li>
      <li class="nav-item">
        <%= link_to "カート", cart_items_path ,class: 'nav-link text-white'%>
      </li>
      <li class="nav-item">
        <%= link_to "ログアウト", destroy_customer_session_path, method: :delete ,class: 'nav-link text-white'%>
      </li>

<% else %>
   <body>
    <body class="d-flex flex-column vh-100">
     <header class="bg-dark text-white">
       <nav class="navbar navbar-expand-lg navbar-dark">
         <div class="container">
           <a class="navbar-brand p-1" href="/" >LOGO</a>
           <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
           </button>
           <div class="collapse navbar-collapse" id="navbarNavDropdown">
             <ul class="navbar-nav ml-auto">
       <li class="nav-item">
        <%= link_to "About", about_path ,class: 'nav-link text-white'%>
      </li>
       <li class="nav-item">
        <%= link_to "商品一覧", items_path ,class: 'nav-link text-white'%>
      </li>

      <li class="nav-item">
        <%= link_to "新規登録", new_customer_registration_path ,class: 'nav-link text-white'%>
      </li>

      <li class="nav-item">
        <%= link_to "ログイン", new_customer_session_path ,class: 'nav-link text-white'%>
      </li>
<% end %>

            </ul>
          </div>
        </div>
      </nav>
    </header>
  <%= flash[:notice] %>

    <main class="mb-auto">
    <%= yield %>
    </main>

   </body>
  <footer>
   <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </footer>
</html>